version: '3.3'

services:
  app:
    container_name: potd_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/potd_social
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - PZ_API_KEY=${PZ_API_KEY}
    depends_on:
      - db
    networks:
      - potd_network

  db:
    image: postgres:15-alpine
    container_name: potd_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: potd_social
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    networks:
      - potd_network

networks:
  potd_network:
    driver: bridge

volumes:
  db_data_prod:
